// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTt60Y1BtM-YxOGhHnX-c8UU8H8eZ5d38',
    appId: '1:518469229366:web:e8aae22e7d952594fff197',
    messagingSenderId: '518469229366',
    projectId: 'simkas-mobile',
    authDomain: 'simkas-mobile.firebaseapp.com',
    storageBucket: 'simkas-mobile.appspot.com',
    measurementId: 'G-LB053HD253',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMasvFEazsFfpB8Y3ku60SbWp23zaT3E',
    appId: '1:518469229366:android:c286543a00cb8910fff197',
    messagingSenderId: '518469229366',
    projectId: 'simkas-mobile',
    storageBucket: 'simkas-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lcNgeQqH5L-PopRLvQG9VP31ondQQfE',
    appId: '1:518469229366:ios:31357fe5ef82adc0fff197',
    messagingSenderId: '518469229366',
    projectId: 'simkas-mobile',
    storageBucket: 'simkas-mobile.appspot.com',
    iosBundleId: 'com.example.mobileSimkas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5lcNgeQqH5L-PopRLvQG9VP31ondQQfE',
    appId: '1:518469229366:ios:4fa0a9f095533072fff197',
    messagingSenderId: '518469229366',
    projectId: 'simkas-mobile',
    storageBucket: 'simkas-mobile.appspot.com',
    iosBundleId: 'com.example.mobileSimkas.RunnerTests',
  );
}
